version: "3"

services:
  api-gateway:
    build: ./src/microservice/sibylla-gateway
    volumes:
      - ./src/microservice/sibylla-gateway/webapp:/usr/src/www
      - ./src/microservice/sibylla-gateway/conf.d:/etc/nginx/conf.d
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.4
  article-api:
    build: ./src/microservice/article-api
    volumes: 
      - ./src/microservice/article-api:/usr/src/app
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.5
  user-api:
    build: ./src/microservice/user-api
    volumes:
      - ./src/microservice/user-api:/usr/src/app
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.6
  auth-api:
    build: ./src/microservice/auth-api
    volumes:
      - ./src/microservice/auth-api:/usr/src/app
      - ./src/certs:/usr/src/certs
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.7
  prophet:
    build: ./src/prophet
    volumes:
      - ./src/prophet:/usr/src/app
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.8
  sweeper:
    build: ./src/sweeper
    volumes:
      - ./src/sweeper:/usr/src/app
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.9
  es-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      sibylla-net:
        ipv4_address: 172.18.0.10

volumes:
  esdata1:
    driver: local

networks:
  sibylla-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
