http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: 172.18.0.4
    paths: 
      - '/api*'
  
serviceEndpoints:
  article-api-svc:
    url: 'http://172.18.0.5:8080'
  user-api-svc:
    url: 'http://172.18.0.6:8080'
  auth-api-svc:
    url: 'http://172.18.0.7:8080'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - condition:
              name: pathMatch
              pattern: /api/article*
            action:
              serviceEndpoint: article-api-svc
              changeOrigin: false
              prependPath: true
              ignorePath: false
              stripPath: true
