http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: altair.latera.kr
    paths: '/api'
  
serviceEndpoints:
  article-api:
    url: 'http://localhost:8081'
  user-api:
    url: 'http://localhost:8082'
  auth-api:
    url: 'http://localhost:8083'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - condition:
              name: pathExact
              path: /article
            action:
              serviceEndpoint: article-api
              changeOrigin: false
