FROM python:3
# FROM ubuntu:18.04
ENV CHROME_DRIVER_PATH /usr/src/app/webdriver/chromedriver
WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get -y install curl
# RUN apt-get -y install python3 python3-pip
RUN apt-get -y install libxss1 libgconf2-4 libappindicator1 libindicator7
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

COPY . .
RUN chmod +x webdriver/chromedriver
RUN pip install --no-cache-dir -r requirements.txt
ENV FLASK_APP src/app
ENV PYTHONUNBUFFERED 1
CMD flask run --host 0.0.0.0 --port 8080