FROM python:3
# FROM ubuntu:18.04
WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get -y install curl
# RUN apt-get -y install python3 python3-pip
RUN apt-get -y install libxss1 libgconf2-4 libappindicator1 libindicator7
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

COPY requirements.txt ./
COPY src ./src
COPY webdriver ./webdriver
RUN pip install --no-cache-dir -r requirements.txt
RUN python src/main.py
