zuul:
  routes:
    article:
      url: http://172.18.0.5:8080
      sensitiveHeaders: Cookie,Set-Cookie
    user:
      url: http://172.18.0.6:8080
      sensitiveHeaders: Cookie,Set-Cookie
    auth:
      url: http://172.18.0.7:8080
      sensitiveHeaders: Cookie,Set-Cookie
    prophet:
      url: http://172.18.0.8:8080
      sensitiveHeaders: Cookie,Set-Cookie
    sweeper:
      url: http://172.18.0.9:8080
      sensitiveHeaders: Cookie,Set-Cookie
    es:
      url: http://172.18.0.10:9200
      sensitiveHeaders: Cookie,Set-Cookie