setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: 5s
setup.dashboards.retry.maximum: 0

output.elasticsearch:
  hosts: ["http://172.18.0.10:9200"]
  max_retries: 0
setup.kibana:
  host: "kibana.sibylla.latera.kr:80"

metricbeat.modules:
  - module: docker
    enabled: true
    period: 10s
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///hostfs/var/run/docker.sock"]