output.elasticsearch:
  hosts: ["http://172.18.0.10:9200"]
setup.kibana:
  host: "http://kibana.sibylla.latera.kr"

metricbeat.modules:
  - module: docker
    enabled: true
    period: 10s
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix://var/run/docker.sock"]